/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonalRouteImport } from './routes/_personal'
import { Route as WorkRouteImport } from './routes/_work'
import { Route as DaysGoneRouteImport } from './routes/days-gone'
import { Route as PersonalAboutRouteImport } from './routes/_personal/about'
import { Route as PersonalWritingRouteImport } from './routes/_personal/writing'
import { Route as WorkExperienceRouteImport } from './routes/_work/experience'
import { Route as WorkProjectsIndexRouteImport } from './routes/_work/projects/index'
import { Route as WorkProjectsSlugRouteImport } from './routes/_work/projects/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/_personal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/_work',
  getParentRoute: () => rootRouteImport,
} as any)
const DaysGoneRoute = DaysGoneRouteImport.update({
  id: '/days-gone',
  path: '/days-gone',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalAboutRoute = PersonalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PersonalRoute,
} as any)
const PersonalWritingRoute = PersonalWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => PersonalRoute,
} as any)
const WorkExperienceRoute = WorkExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => WorkRoute,
} as any)
const WorkProjectsIndexRoute = WorkProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkProjectsSlugRoute = WorkProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/days-gone': typeof DaysGoneRoute
  '/about': typeof PersonalAboutRoute
  '/writing': typeof PersonalWritingRoute
  '/experience': typeof WorkExperienceRoute
  '/projects/$slug': typeof WorkProjectsSlugRoute
  '/projects/': typeof WorkProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/days-gone': typeof DaysGoneRoute
  '/about': typeof PersonalAboutRoute
  '/writing': typeof PersonalWritingRoute
  '/experience': typeof WorkExperienceRoute
  '/projects/$slug': typeof WorkProjectsSlugRoute
  '/projects': typeof WorkProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_personal': typeof PersonalRouteWithChildren
  '/_work': typeof WorkRouteWithChildren
  '/days-gone': typeof DaysGoneRoute
  '/_personal/about': typeof PersonalAboutRoute
  '/_personal/writing': typeof PersonalWritingRoute
  '/_work/experience': typeof WorkExperienceRoute
  '/_work/projects/$slug': typeof WorkProjectsSlugRoute
  '/_work/projects/': typeof WorkProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/days-gone'
    | '/about'
    | '/writing'
    | '/experience'
    | '/projects/$slug'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/days-gone'
    | '/about'
    | '/writing'
    | '/experience'
    | '/projects/$slug'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_personal'
    | '/_work'
    | '/days-gone'
    | '/_personal/about'
    | '/_personal/writing'
    | '/_work/experience'
    | '/_work/projects/$slug'
    | '/_work/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonalRoute: typeof PersonalRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
  DaysGoneRoute: typeof DaysGoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_personal': {
      id: '/_personal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_work': {
      id: '/_work'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/days-gone': {
      id: '/days-gone'
      path: '/days-gone'
      fullPath: '/days-gone'
      preLoaderRoute: typeof DaysGoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_personal/about': {
      id: '/_personal/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PersonalAboutRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/_personal/writing': {
      id: '/_personal/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof PersonalWritingRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/_work/experience': {
      id: '/_work/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof WorkExperienceRouteImport
      parentRoute: typeof WorkRoute
    }
    '/_work/projects/': {
      id: '/_work/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof WorkProjectsIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/_work/projects/$slug': {
      id: '/_work/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof WorkProjectsSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface PersonalRouteChildren {
  PersonalAboutRoute: typeof PersonalAboutRoute
  PersonalWritingRoute: typeof PersonalWritingRoute
}

const PersonalRouteChildren: PersonalRouteChildren = {
  PersonalAboutRoute: PersonalAboutRoute,
  PersonalWritingRoute: PersonalWritingRoute,
}

const PersonalRouteWithChildren = PersonalRoute._addFileChildren(
  PersonalRouteChildren,
)

interface WorkRouteChildren {
  WorkExperienceRoute: typeof WorkExperienceRoute
  WorkProjectsSlugRoute: typeof WorkProjectsSlugRoute
  WorkProjectsIndexRoute: typeof WorkProjectsIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkExperienceRoute: WorkExperienceRoute,
  WorkProjectsSlugRoute: WorkProjectsSlugRoute,
  WorkProjectsIndexRoute: WorkProjectsIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonalRoute: PersonalRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
  DaysGoneRoute: DaysGoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
